### ISSUE TITLE
csdl-to-json-convertor fails on valid edm types 

### ISSUE THREAD

**Issue by rahlvers** [DMTF/Redfish-Tools#1]
The list of missing types for the JSON schema generator:
• Edm.Duration
• Edm.NavigationPropertyPath
• Edm.PropertyPath
• Edm.SByte
• Edm.TimeOfDay

**Comment by rahlvers** [comment]
For SSM members, open issues with more information: https://github.com/SNIA/SSM/issues/401 and https://github.com/SNIA/SSM/issues/400

**Comment by pboyd04** [comment]
There is no equivalent in JSON to Duration or TimeOfDay. Should we just require the CSDL to use RegEx strings for this?

**Comment by mraineri** [comment]
@rahlvers is there any need to add Edm.PropertyPath and Edm.NavigationPropertyPath? As far as I can tell they aren't used currently, and we did update the tool a while ago to add the other types.

**Comment by mraineri** [comment]
Closing; if we need Edm.PropertyPath or Edm.NavigationPropertyPath, please reopen.
