### ISSUE TITLE
csdl-to-json.py "Missing "Type" attribute for tag "Property"

### ISSUE THREAD

**Issue by seiferteric** [DMTF/Redfish-Tools#103]
When converting output of yang to csdl converter tool to json schema, all of the Property fields are missing in the resultant json . These errors are shown when running:

```
Generating JSON for: openconfig_interfaces.interfaces.interface.hold_time.config_v1.xml
-- ERROR: Missing "Type" attribute for tag "Property"
-- ERROR: Could not resolve reference to "UNKNOWN_ATTRIB" for "UNKNOWN_ATTRIB"
-- ERROR: Missing "Type" attribute for tag "Property"
-- ERROR: Could not resolve reference to "UNKNOWN_ATTRIB" for "UNKNOWN_ATTRIB"
-- Errors detected while generating ./interfaces_out/openconfig_interfaces.interfaces.interface.hold_time.config.v1_0_0.json; not creating file
Generating JSON for: openconfig_interfaces.interfaces.interface.state_v1.xml
...
```

**Comment by mraineri** [comment]
When a "Property" instance is used in CSDL, there needs to be a corresponding "Type" facet to indicate the data type used. This doesn't sound like a problem with the CSDL to JSON converter, but rather the CSDL itself is malformed. Are you able to share the file openconfig_interfaces.interfaces.interface.hold_time.config_v1.xml?

**Comment by seiferteric** [comment]
Yes you are right, it is the output from the pyang version of the YANG to Redfish converter, there is no type facet.
