### ISSUE TITLE
Doc generator - add 'required' tags to Properties and Action Parameters

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#108]
In the Property Tables and Parameters tables for Actions, it would be good to have those properties/parameters that are Required to be tagged in the document. 

Required parameters will contain: "requiredParameter": true 
Required properties will be listed in the schema within the "required"[] array at the object/resource level.

**Comment by akf** [comment]
I think we already have this on properties, unless I'm missing something. Maybe we didn't in May?

**Comment by jautor** [comment]
Yes, the support is in there.  Closed...
