### ISSUE TITLE
Request for "Broker" Redfish API

### ISSUE THREAD

**Issue by john24318** [DMTF/Redfish-Tools#116]
Hi DMTF,
Could you design a centralized "Brokers" redfish API to consolidate the sensor readings?
If I want to get power consumption, thermal, Intel ME readings... etc., I have to invoke the Systems or Chassis API subcomponent many times. Is it possible to design a "broker" settings to deliver sensor reading value for management software in the future? It will be more convenient to monitor servers.
Sorry for that I don't know how to give my feedback, so I leave message here.

Sincerely,
John

**Comment by jautor** [comment]
Hi John, thanks for the feedback, and should post this in the Redfish Forum (www.redfishforum.com), as it's a feature request for the Redfish Specification, not just the open source tools.  

But I can tell you that the group is looking at more generalized sensor definitions and has a Data Center Infrastructure Management (DCIM) Task Force looking at this issue.  There is a "work in progress" release of that work on the DMTF standards site (www.dmtf.org/standards/redfish) - specifically here: https://www.dmtf.org/sites/default/files/standards/documents/DSP-IS0005_0.2a.zip 

And you should expect to see another WIP release soon.

**Comment by mraineri** [comment]
If you'd like to discuss new functionality in the standard or new tool ideas, please raise this on the public forum found here: https://redfishforum.com/
