### ISSUE TITLE
Automatically include json payload and action examples

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#127]
Add a config option to specify a folder that contains JSON payload examples, and use a filename format to automatically match examples with schemas and Action definitions.  The current process uses individual entries in the Input file to specify examples - this would remove that burden to keep those entries up to date. 

Suggest a simple naming structure that ties to Schema Name (open to easier / better suggestions):
 - [SchemaName]-v1-example.json
 - [SchemaName]-v1-action-[ActionName].json

e.g.

 - ComputerSystem-v1-example.json
 - ComputerSystem-v1-action-Reset.json

This style also makes updates to the examples simple by only using major version.

Obviously the current tag/include method should be retained as well.

**Comment by akf** [comment]
👍

**Comment by akf** [comment]
Implemented just as described in the issue. Payloads for Action examples are a new feature; they are simply included with the Action details -- immediately above in the case of markdown output; immediately below for HTML output.
