### ISSUE TITLE
Type names with alias are not recognized

### ISSUE THREAD

**Issue by dorado18** [DMTF/Redfish-Tools#129]
Hello,

When trying to convert a set of csdl files generated by Yang-to-Redfish into json we get some errors:
```

$ python csdl-to-json.py --input ./interfaces/output_dir --output ./output_dir
Generating JSON for: SessionService_v1.xml
Generating JSON for: MessageRegistry_v1.xml
Generating JSON for: openconfig_if_ethernet.ethernet_top_v1.xml
-- ERROR: Could not resolve reference to "ethernet" for "ethernet.ethernet"
-- Errors detected while generating ./output_dir/openconfig_if_ethernet.ethernet_top.v1_0_0.json; not creating file
...
```

I am attaching a [tar.gz](https://github.com/DMTF/Redfish-Tools/files/2315473/interfaces.tar.gz) with the CSDL files.

I believe that the problem is that the function 'csdl_type_to_json_type' in file csdl-to-json.py can't handle types that are named using an alias, like for example in the error above, the 'ethernet' alias is defined as 

```xml
<edmx:Reference Uri="http://redfish.dmtf.org/schemas/v1/openconfig_if_ethernet.ethernet_top.ethernet_v1.xml">
  <edmx:Include Namespace="openconfig_if_ethernet.ethernet_top.ethernet" Alias="ethernet"/>
</edmx:Reference>
```

Could you confirm that?

Thanks,
andre

**Comment by mraineri** [comment]
No, it doesn't handle that type of conversion right now. Will have to think about this a bit more to see if it makes sense to add aliasing like this, and if it is, then we need to add that linkage to the CSDL to JSON converter.
