### ISSUE TITLE
Add section for referenced schemas

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#170]
Need a separate section in the document output to provide documentation for 'referenced' schemas that come from other sources. 

This would essentially be an ability to insert schema docs from additional sources (not just the json-schema directory).  Best if this ability is added as #include tags within the Input file, as these references should be file-specific, not "everything in this folder".

**Comment by mraineri** [comment]
@jautor is this already handled now?

**Comment by jautor** [comment]
Yes, the `import_from` config file option allows for multiple references, and supports wildcards for folder-level references.
