### ISSUE TITLE
Allow for HTML / MD input file for Property Index output

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#173]
Need the input Markdown document (like is done for the schema guide output) for merging the introduction / document identification template along with change log.  This support should be limited to just providing HTML/MD to surround the property index output - a .MD input file with a single marker for "&lt;insert property index here&gt;" or similar solution would be sufficient.

**Comment by akf** [comment]
Implemented as suggested. The marker is "[insert property index]"

**Comment by akf** [comment]
Discussed with @jautor that this isn't implemented quite the way he had in mind. The supplemental file should be markdown (which may, as always, include HTML) regardless of output format. So I'll be making this change: 

Assume supplemental file is markdown, if producing HTML, convert to HTML (as with other modes).

README_Property_Index.md will state that something like: "In property index mode, the supplemental material document should be a markdown file containing content to be included before/after the property index, and a marker "[insert property index]" where the generated property index should go. No configuration will be read from the supplemental file."
