### ISSUE TITLE
CSDL->JSON converter: inconsistent sorting for enum strings vs enum string descriptions

### ISSUE THREAD

**Issue by billschererhpe** [DMTF/Redfish-Tools#187]
When translating a batch of enumeration values, the CSDL->JSON tool is alphabetizing enum descriptions but leaving the enum values unsorted.  (See below for example).  Can we make the tool be consistent please?

Example output:
        "FooTableEntry": {
            "description": "An assignment of foo.",
            "enum": [
                "strict",
                "ABC",
                "DEF",
                "vendor"
            ],
            "enumDescriptions": {
                "ABC": "ABC algorithm.",
                "DEF": "DEF algorithm.",
                "strict": "Strict algorithm.",
                "vendor": "Vendor specific algorithm"
            },
            "type": "string"
        },

In case it's helpful, the enum list at the top in my sample matched the CSDL ordering. The enumDescriptions block is clearly sorted alphabetically.

**Comment by mraineri** [comment]
The challenge with that is we'll get into the realm of hand crafting JSON from strings, rather than exporting it from a Python dictionary. Unfortunately Python dictionaries have no way of guaranteeing order of elements in a dictionary, meaning we can't easily make that sort of correlation.

**Comment by mraineri** [comment]
Discussion 8/28: Closing; while it would be nice to make them consistent, we'd like to keep the conversion simple, and also avoid reorganizing the list in case others folks notice and wonder why it changed.
