### ISSUE TITLE
Create $Metadata document

### ISSUE THREAD

**Issue by GEricson** [DMTF/Redfish-Tools#21]

**Comment by mraineri** [comment]
What's this in reference to? Tools don't generate $metadata documents; that's the service's responsibility.

**Comment by GEricson** [comment]
True, but creating the format (CSDL or JSON Schema) at the metadata level of describing the schema is not trivial and should be automated.  As I read the OData specs, the metadata document consists of the set of supported schema represented as instances of the metadata.

**Comment by mraineri** [comment]
That's true, but a given service doesn't necessarily support all schemas, nor will it necessarily support the same version level of the given schemas.

The way $metadata is constructed on Redfish services is not to include the contents of all schemas directly; just simply reference the proper schema. The $metadata resource found in the development mockup is a complete example of a service's $metadata resource.

**Comment by GEricson** [comment]
Agree.  I'm thinking of this as an aid to developers.  The tool could output a separate $metadata file for each translated CSDL file, or could accept a manifest listing the supported schema and output a consolidated $metadata document conforming to the manifest.

**Comment by pwvancil** [comment]
plan is to create a  separate white paper doc for how to create a $metadata

this feature not a charter of the CSDL to JSON tool
the contents is actually implementation dependent

**Comment by pwvancil** [comment]
consensus to close:  9/8/16
