### ISSUE TITLE
Add 'format' details to data type column for 'string' 

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#212]
The "format" schema annotation gives useful information about string type properties to show where there is structure or other standardized formats for the string.

Add parenthetical notations for the commonly used "format" values for Redfish, following the style used for showing (enum):
"uri": "string (URI)"
"uri-reference":  "string (URI)"
"data-time": "string (date-time)"

**Comment by akf** [comment]
The above commit(s) add this to markdown and HTML output.
