### ISSUE TITLE
schema guide gives incorrect enum for GraphicalConsole ConnectTypesSupported

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Tools#227]
http://redfish.dmtf.org/schemas/DSP2046_2019.1.html#Manager
https://redfish.dmtf.org/schemas/v1/Manager.v1_5_2.json

In the JSON schema, "ConnectTypesSupported" under "GraphicalConsole" is an enum of ["KVMIP", "Oem"]. But in the schema guide, it says the ConnectTypesSupported for GraphicalConsole is the same as for "CommandConnectTypesSupported", which is a different list.

**Comment by jautor** [comment]
Great find!  This is an unusual corner case in the Redfish Schema where there are two properties with the same name (in the same schema), both with enumeration definitions, but with a different set of values.  The tool obviously didn't account for that case.  We will need to figure out a way to deal with this without affecting the readability of the output in all other cases.

**Comment by blakehilliard** [comment]
I just noticed this also affects the `Type` for Attributes in AttributeRegistry. It shows the enum for `DependencyType` when it should instead show `AttributeType`.

http://redfish.dmtf.org/schemas/DSP2046_2019.2.html#AttributeRegistry
https://redfish.dmtf.org/schemas/AttributeRegistry.v1_3_2.json
