### ISSUE TITLE
Doc Generator: Description Override doesn't appear to be working.

### ISSUE THREAD

**Issue by barbara9** [DMTF/Redfish-Tools#264]
I'm trying to create a sub-profile using the examples in github and I'm trying to override the Description in several properties in my profile.  Specifically, I want to change the ComputerSystem.Processors Description. I tried using the below DescriptionOverride in the config.json file and it didn't work.

	"DescriptionOverrides": {
		"Processors": [
			{
				"description": "The link to the collection of accelerator processors (GPU, FPGA, etc) associated with this system.",
				"overrideDescription": "The link to the collection of accelerator processors (GPU, FPGA, etc) associated with this system.",
				"type": "string",
				"schemas": [
					"ComputerSystem"
				]
			}
		],

I tried using the below "Description Overrides" section header from the userssupplement.md in my markdown file and that didn't work either.

# Description Overrides

* Processors: The link to the collection of accelerator processors (GPU, FPGA, etc) associated with this system.

**Comment by akf** [comment]
I can see that DescriptionOverrides in the config file is used only in "property index" mode, not in subset mode. (This is almost certainly an oversight; I can see that it makes perfect sense to use this in subset mode and it would give you better control over the overrides than putting them in the supplemental markdown.) 

What you show for the usersupplement.md should work, provided that you're using an asterisk (*) for the bullet point. Also, there should be no space before the asterisk. Markdown offers a number of ways to get that effect, but the doc generator's parsing is more particular.

**Comment by barbara9** [comment]
Yes.  It would be very useful to be able to use the Description Overrides in the config file in subset mode.

In the markdown document, I donot have a space before the asterisk and I tried placing the Description Override section in a couple places in the markdown document.  It doesn't work.  What I'm expecting to see in my html document is the ComputerSystem schema table with Processors in the first column and my description in the last column.  What I see in that last column is the description from the schema.

**Comment by akf** [comment]
"I tried placing the Description Override section in a couple places in the markdown document." This gave me an idea! I notice that our example includes "Description Overrides" (plural) as a top-level heading (along with other definitions) before showing an example of how to actually use it -- in a section for a schema under "Schema Supplement." 

To confirm, it should look like this:

=======================================================

# Schema Supplement

[ Possibly sections for other schemas, but not another top-level heading ]

## ComputerSystem

[ Possibly more data here, but no second-level heading ]

### Description Overrides

* Processors:  The link to the collection of accelerator processors (GPU, FPGA, etc) associated with this system.

=======================================================

**Comment by barbara9** [comment]
I did use "Description Overrides" (plural) in my doc.  Typo in my github issue.  

I tried the following in the markdown document and it didn't work.  Under "#Schema Supplement" I put "## ComputerSystem" and under that I put "### Description Overrides" and then "* Processors: xxxx".  I also tried using a single "#" for ComputerSystem and Description Overrides, and that didn't work either.

# Work in Progress Schema Reference Guide

# Schema Supplement

## ComputerSystem

### Description Overrides

* Processors: The link to the collection of accelerator processors (GPU, FPGA, etc) associated with this system.

# Postscript

**Comment by barbara9** [comment]
If it helps I can attach all the input files, the config.json, Profilexxxx.md and Profilexxxx.json and the resulting Profilexxxx.html.

**Comment by akf** [comment]
I'm sure that would help! Let me know what you're specifying on the command line as well. Thanks!

**Comment by akf** [comment]
It looks like you've found a bug (or two). Your markdown syntax is good, and if you do exactly the same thing for the PowerState parameter, it works. I have some theories about what might be going on, but I have a bit of digging to do on this one.

**Comment by akf** [comment]
Hi @barbara9, I'm sorry I wasn't able to jump on debugging this immediately, because it turned out to be a small fix. 

You do still need to use the markdown document to specify the overrides in all but property index mode.
