### ISSUE TITLE
Move multiple referenced objects to Property Details

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#269]
For resources with multiple instances of the same object (referenced either in the same schema or an external schema reference), collapse these objects to a new table under Property Details and provide a reference in the main property table.  

Example - the `Thresholds` object in `Sensor` contains a number of sub-objects all based on the same object-level definition.  Instead of repeating the same object (making the table quite large), the object would just reference a table "See Property Details below" and collapse the entry into a single line.

This function should not affect "common object" handling of external references.  

Recommend that this be added as a config option, likely with a count at which objects are collapsed in this way.  Meaning, the user may wish schemas with two uses of an object definition to appear in-line, but three or more uses to be collapsed.

**Comment by akf** [comment]
I've merged in some updates that I believe address this.
