### ISSUE TITLE
Add ISO text around generated tables

### ISSUE THREAD

**Issue by sbs-jms** [DMTF/Redfish-Tools#282]
[ISO directives](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor413) call for each table to be captioned, and referenced in the specification text. Something like:

> Table 3 summarized the properties required in an instance of foo.
>  |Property    | Value  |
> |--|--|
> |P1| true|
>
> Table 3: Required foo properties

**Comment by sbs-jms** [comment]
Here is a patch of the changes that I'm using in Swordfish today. 
[suggested_patch.txt](https://github.com/DMTF/Redfish-Tools/files/5076180/suggested_patch.txt)

**Comment by mraineri** [comment]
@sbs-jms with your PR merged, is this still an issue?

**Comment by sbs-jms** [comment]
There may be some additional minor changes as our toolset moves toward a pure-pandoc approach, but this particular issue can be closed.
