### ISSUE TITLE
Doc-gen - Read-write Links showing as read-only

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#296]
Multiple cases where a link (generally speaking, an object with a single @odata.id property) is marked in schema as readonly=false (RW), but are showing up in generated documents as "read-only".

Easy examples to see are in Facility schema (as it's a v1.0 schema), where the Contains/ContainedBy links are reported as read-only.

**Comment by akf** [comment]
There were two issues here:

1. When gathering data for a $ref in an "items" object, the doc generator wasn't carrying through the "readonly" value from the parent object. Example: ContainsFacilities
2. Similarly, when not in an "items" object, the "readonly" value was just plain being set to True when constructing data to present as a Link. (The doc generator cobbles together a basic summary object in this case, and probably when I initially wrote this I had the incorrect impression that links weren't writable.) Example: ContainedByFacility
