### ISSUE TITLE
Add "format" keyword "duration" support for Edm.Duration values in JSON schema

### ISSUE THREAD

**Issue by seanb-c** [DMTF/Redfish-Tools#307]
I think this PR:
https://github.com/json-schema-org/json-schema-spec/pull/718/commits/f0f802f21f9fab8fd57c6c9712018f9d938e9047
implies that JSON schema supports a duration format. I think this would be useful to add to the Redfish schema files, because duration will often times have a very specific purpose programmatically.

I think (but haven't tested) that this diff would do it:
```
diff --git a/csdl-to-json-convertor/csdl-to-json.py b/csdl-to-json-convertor/csdl-to-json.py
index 16aa30f..2c2fb17 100644
--- a/csdl-to-json-convertor/csdl-to-json.py
+++ b/csdl-to-json-convertor/csdl-to-json.py
@@ -1192,10 +1192,11 @@ class CSDLToJSON:
         elif type == "Edm.Duration":
             if is_nullable:
                 json_type = [ "string", "null" ]
             else:
                 json_type = "string"
+            format = "duration"
             pattern = "-?P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?"
         elif type == "Edm.TimeOfDay":
             if is_nullable:
                 json_type = [ "string", "null" ]
             else:
```

**Comment by seanb-c** [comment]
@J2Hilland, FYI.

**Comment by mraineri** [comment]
I'm not sure we can leverage this at this time. Currently we point to JSON Schema Draft 07, and if I'm reading the JSON Schema change log correctly, "duration" was added in Draft 09.

**Comment by mraineri** [comment]
Closing; can't add this at this time. However, if we ever migrate to Draft 9 in the future, we can revisit this then.

**Comment by seanb-c** [comment]
@mraineri, Just out of a curiosity: I assume that at some point we'll migrate? Is it generally a big process or are they good enough with backwards compatibility that we could quickly make the change fairly easily if there was a more compelling reason?

**Comment by mraineri** [comment]
At least from what @jautor has been telling me, there are a number of technical challenges we'd need to solve if we were to go from Draft 7 to Draft 9; some of it doesn't seem backwards compatible from how we do some of the things we do today.

In the past though, when we went from Draft 4 to Draft 7, it was an easy switch since that type of jump didn't pose any challenges.
