### ISSUE TITLE
Add config option for table numbering and references

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#335]
Need to add a configuration option to enable/disable the addition of the table reference and numbering feature.  The new functionality added should be optional as it requires additional processing after document generation (which, if not desired, should not be required).

Note that while the new functionality is targeted at the Markdown output, it does leak into HTML output in the Revision History ribbon.  (not sure if that was intentional or not)  The addition of the release/version row headers on the ribbon should always be included (not part of the table numbering option).

**Comment by akf** [comment]
I've added this to our list for the next batch of work. What's the urgency -- do you need to be able to turn this off for the current round of documentation you're generating, or are you using the ISO support?

**Comment by jautor** [comment]
Not a rush now – I made the manual fixes in the output for us to publish this week, so we’ve got 3 months now to deal with the ISO stuff and anything else, too…  It wasn’t much work on my side.

Thanks,

Jeff
