### ISSUE TITLE
Doc generator - no output in markdown format using "[insert property index]"

### ISSUE THREAD

**Issue by rahlvers** [DMTF/Redfish-Tools#339]
Getting output in html mode, output file is completely blank in markdown mode.

[build.zip](https://github.com/DMTF/Redfish-Tools/files/5870908/build.zip)

**Comment by akf** [comment]
Big miss on my part here! We recently introduced a new output format, "slate," which is the markdown format the doc generator used to produce. The "markdown" format differs mainly in terms of heading levels (and is surely what you want). The miss is that property index mode works for "slate" and not for "markdown." This is probably an easy fix; I'm looking into it now. 

FYI, you no longer need to (or should) put the "[insert property index]" string in the boilerplate. Now you can provide a boilerplate_intro and a boilerplate_postscript, and the generated documentation will be put in between them -- or you can omit both or either of these boilerplate files.

**Comment by akf** [comment]
Happily, this was a trivial fix, merged in as PR #341 . You can pull the latest code if you want to, or you can specify "slate" instead of "markdown." For the property index, the two formats are identical.
