### ISSUE TITLE
Mockup syntax test doesn't point to file

### ISSUE THREAD

**Issue by billschererhpe** [DMTF/Redfish-Tools#344]
The Travis syntax validation for the public-acd mockup reported that a file was failing to pass JSON syntax (ultimately because of a stray comma), but it didn't tell me which file was actually responsible. There were over 150 JSON files added in that mockup, so tracking it down was very difficult. It would be great if the test could be augmented to give the file in which the error was detected. (And since most JSON files in mockups are named index.json, the path would also be helpful.)

**Comment by mraineri** [comment]
At least in the meantime, I've been using this from the command line from the mockups directory to track down JSON errors.
`find . -name \*.json  | xargs -I {} jsonlint-php -q {}`

I've gotten output like this, which points to a specific file:
```
./development/Chassis/GenZ/Memory/index.json: Parse error on line 32:
.../8/"        },    ]}
--------------------^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - It appears you have an extra trailing comma
```

**Comment by jcleung5549** [comment]
I use jsonlint-tree on my mockup directories before running Travis - https://github.com/educastellano/jsonlint-tree

$> jsonlint-tree myfolder
