### ISSUE TITLE
Add config option to warn on missing example payloads

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#366]
As response payload examples (and for action responses) are picked up automatically from a folder when specified, it would be helpful to throw a warning when an example is NOT found - since the intent of the output is to fully document the schemas.  But making it an option to not annoy other users makes sense...

**Comment by akf** [comment]
Which is the default, "nag" or "don't nag"?

**Comment by jautor** [comment]
The universal default should always be "don't nag"... :smile: 

(I will turn the option on as I'll use the feature, but don't expect all use cases would want that)

**Comment by akf** [comment]
"warn_missing_payloads"
