### ISSUE TITLE
Doc Generator doesn't use provided URI for collecting schema mockups.

### ISSUE THREAD

**Issue by lukasz-tuz** [DMTF/Redfish-Tools#393]
When using an URI for "mockup" attribute in content supplement json, Doc Generator logs a warning:

`UserWarning: Unable to retrieve Mockup from URL "<schema_uri>/index.json": name 'urllib' is not defined`

Generated document doesn't contain any mockups.

Seems like the only fix required is adding 'import urllib' in doc_generator.py.

Redfish-Tools version I was using: `ebe1e23d454cd11c83d32ca2112bc1536492d485`.

**Comment by akf** [comment]
Thanks, @lukasz-tuz!
