### ISSUE TITLE
(openapi-generator-cli) Generation of client from OpenAPI schema fails due to presence of '/redfish/v1/$metadata' path

### ISSUE THREAD

**Issue by mick-jones-vertiv** [DMTF/Redfish-Tools#410]
OpenAPI generator CLI (https://github.com/OpenAPITools/openapi-generator) client generator fails with error: 
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for '/redfish/v1/$metadata'

It explicitly has a problem with the '/redfish/v1/$metadata' path. Removing the "$" allows generation to complete.

1) Validation is successful. Error only occurs on generation of a server or client SDK.
2) Other tools also validate successfully.

Question: Is this an issue with the schema or a downstream tool error? RFC2396 suggests that this format of URI is not permitted and hence the generation parsing fails? Refer to: https://www.ietf.org/rfc/rfc2396.txt

**Comment by mick-jones-vertiv** [comment]
Confirmed issue with openapi-generator. Leaving this here for reference, but this can be closed.

The Swagger Codegen tool works without issue:
https://github.com/swagger-api/swagger-codegen

Here's an example of the command using Swagger Codegen to generate a single local file from remote schema:
"java -jar .\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -l openapi-yaml -i  http://redfish.dmtf.org/schemas/v1/openapi.yaml -o gen\openapi-yaml"

**Comment by mraineri** [comment]
Since "/redfish/v1/$metadata" is a required URI (defined by OData that Redfish inherited), I'm not entirely sure how we can work around this.

From a legality perspective, it seems like it is a permitted URI. Appendix A of the referenced RFC defines characters in a URI segment to be:

```
      pchar         = unreserved | escaped |
                      ":" | "@" | "&" | "=" | "+" | "$" | ","
```

and $ is in that list of allowable segment characters.

**Comment by mraineri** [comment]
Closing as a tooling issue with OpenAPI
