### ISSUE TITLE
Generating document base on redfish server get response for standard schema

### ISSUE THREAD

**Issue by plmanik** [DMTF/Redfish-Tools#416]
Hi,
I understand this tool can be used to generate document based on schema file. Is it possible to generate document based on redfish server get response based on standard schema?
Assume I can provide Redfish server IP, username, password and it can generate document based on get response of all URI's
Please let me know whether this can be possible with this tool or any other redfish tool available 

Thanks,
Mani

**Comment by mraineri** [comment]
At this time, this is not in scope for what we have for tools.

There are OpenAPI tools where you should be able to point them at your service's OpenAPI file, and that should get everything remotely, but those tools are owned by various OpenAPI groups.

Using the documentation generator tool we have is all JSON Schema-based, so you'd need to iterate over your service's JSON Schema files, download them, then run the tool.

**Comment by mraineri** [comment]
Closing; at this time this sort of tool is out of scope.
