### ISSUE TITLE
csdl-syntax-test should validate Type attribute of Property element in a csdl file

### ISSUE THREAD

**Issue by rahkr** [DMTF/Redfish-Tools#422]
This issue stems from https://github.com/DMTF/Redfish/issues/5177 which calls out Edm.PrimitiveType usage in AttributeRegistry_v1.xml. It is understood that usage of Edm.PrimitveType is discouraged but without a test this knowledge can only be documented without an enforcement. The existing test csdl-syntax-test.js does not check Type attribute against a set of allowed types.

Can we add a test to check if Property Element has type attribute adhering to the rules listed in the redfish specification and described below?
• A qualified name that references an enum type element.
• A qualified name that references a complex type element.
• A primitive data type.
• An array of the previous names or types by using the Collection term

**Comment by mraineri** [comment]
Closing; enhancement merged
