### ISSUE TITLE
Additional CSDL validation for edmx:Reference and for OData.AutoExpandReference

### ISSUE THREAD

**Issue by DryHumour** [DMTF/Redfish-Tools#439]
Very minor CSDL violations in Redfish DSP8010_2022.3 and Swordfish 1.2.4a schema.  Likelihood of actual functional impact is quite low.

- the Uri in an edmx:Reference must be unique [OData XML CSDL 4.0 errata 3](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752505)
- the OData.AutoExpandReferences annotation can only be applied to NavigationProperty (and not Property) [OData Core Vocabulary 4.0 errata 3](https://github.com/oasis-tcs/odata-vocabularies/commit/83bdbd2df1d23091ff142d434d4f0d7141bee622#diff-dcf5fc19e169038982c471b25335ea69c439b132bb02f095dbc47eb34ee06b02R242)

Originally reported on [Redfish forums](https://redfishforum.com/thread/801/extremely-minor-nits-redfish-schema); re-filed here by request.

[DSP8010_2022.3.patch](https://github.com/DMTF/Redfish-Tools/files/10709523/DSP8010_2022.3.patch)
[Swordfish_v1.2.4a_Schema.patch](https://github.com/DMTF/Redfish-Tools/files/10709525/Swordfish_v1.2.4a_Schema.patch)

**Comment by rahlvers** [comment]
Cross reference to Swordfish - issue https://github.com/SNIA/SSM/issues/2071
