### ISSUE TITLE
Same annotation applied to TypeDefinition and where TypeDefinition is used

### ISSUE THREAD

**Issue by cdjaneczek** [DMTF/Redfish-Tools#45]
from OData CSDL spec section 11.1.3
"Annotations MAY be applied to a type definition, and are considered applied wherever the type definition is used. Applying the same annotation to a property whose type definition already defines that annotation is an error."

Org.Odata.Core.V1.xml defines the Tag TypeDefinition and attaches a Description annotation to it
```
<TypeDefinition Name="Tag" UnderlyingType="Edm.Boolean">
    <Annotation Term="Core.Description" String="This is the type to use for all tagging terms"/>
</TypeDefinition>
```

There are usages of that TypeDefinition which also apply the Core.Description annotation
```
<Term Name="DereferenceableIDs" Type="Core.Tag" DefaultValue="true" AppliesTo="EntityContainer">
    <Annotation Term="Core.Description" String="Entity-ids are URLs that locate the identified entity"/>
</Term>
<Term Name="ConventionalIDs" Type="Core.Tag" DefaultValue="true" AppliesTo="EntityContainer">
    <Annotation Term="Core.Description" String="Entity-ids follow OData URL conventions"/>
</Term>
```

The issue is now that the Core.Description Annotation is applied twice to the Terms that are of type Core.Tag

**Comment by mraineri** [comment]
Closing; while this is a bug in the current errata 3 version of the 4.00 definitions, the 4.01 CSDL spec actually relaxes this rule. From the 4.01 version of the spec:
> It is up to the definition of a term to specify whether and how annotations with this term propagate to places where the annotated type definition is used, and whether they can be overridden.
