### ISSUE TITLE
Spurious error message

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Tools#46]
The CSDL Validator displays the following message.
"Could not open http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml"

Despite the message
-       The validator is reporting errata on the schema file
-       The URI path directly from a Chrome browser.

Reproduction notes: Windows 7, Python 3.5, using validator on a single CSDL file.

**Comment by mraineri** [comment]
I've traced it down to an exception being thrown by urllib when trying to access the file, in particular it's throwing a Connection Reset by Peer exception. This doesn't seem to happen all the time though. Apparently other people also using urllib do get this exception from time to time and have worked around it by simply retrying when that sort of exception is thrown.
