### ISSUE TITLE
Expand 'units' abbreviations for clarity in doc-generator

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#60]
The units of measure as shown in the data type column come from the schemas (as designed).  But as these appear fairly infrequently in the resulting document, the abbreviations can be confusing without context.
Adding a simple string-replacement table for common units would improve readability:

Examples 
Current:  number (s)
Replace:  number (seconds)

Current: number (Mb/s)
Replace: number (Mbits/second)

**Comment by akf** [comment]
I think this meets the need. Just realized you may have meant for me to use your example for the format of the replacement table, @jautor! Let me know if what I did suits -- it relies on pipe-delimited markdown tables: 

| Value         | Replacement      |
| s                | seconds              |

**Comment by mraineri** [comment]
Fixed by #67
