### ISSUE TITLE
Schema URI Mapping doesn't allow inclusion of local schema changes or extensions

### ISSUE THREAD

**Issue by sbs-jms** [DMTF/Redfish-Tools#65]
The Schema URI Mapping directive only allows translation of local-path schema objects to URI-path objects. It doesn't allow URI-path schema to be supplemented by local-path schema. For example:

> # Schema URI Mapping
> ## Local-repo: http://redfish.dmtf.org/schemas/swordfish/v1 ../../SSM/json_schema/

Will not expand the parsed schema to be the union of the remote definitions (found via URI) and the local defintions (found by file path).

**Comment by rahlvers** [comment]
Doc generator issue.

**Comment by akf** [comment]
That is true! That was my understanding of what was requested. I dug up the original request, which had language very similar to what appears in the usersupplement.md file (and which I now realize is ambiguous): 

> The doc generator will use the local files when specified and otherwise follow the full URI, including data from remote files if possible.

I understood this as a straight mapping -- if the schema calls for a URI matching A, look for it in the local path B. If I understand what you were expecting, it would be a bit more work, so I'd want to be clear on the requirement.

**Comment by sbs-jms** [comment]
What would be helpful for the Swordfish team is to provide something more akin to a search path, than to a path replacement. Ideally, the code would parse one entry in the supplement file (or combine a number of separate entries) into the equivalent of a PATH variable, and then walk each named element (either filesystem path of URI) to resolve required schema

**Comment by mraineri** [comment]
@sbs-jms and @akf is this still an issue or needs any addressing on the part of the doc generator?

**Comment by mraineri** [comment]
8/16: Closing; have not heard of this issue in recent months. Please reopen if the issue persists.
