### ISSUE TITLE
os.path.isdir() call in parse_supplement.py fails under cygwin

### ISSUE THREAD

**Issue by sbs-jms** [DMTF/Redfish-Tools#66]
Debug statements show that abs_local_path (line ~483) is properly set, and refers to a valid directory, but the isdir() test fails, causing a parsing error.

\# Schema URI Mapping
\#\# Local-repo: http://redfish.dmtf.org/schemas/swordfish/v1 ../../SSM/json_schema/

OS: Windows 7 (current patches)
Python: 3.6.1
Cygwin bash: 4.4.12(3), x86_64

**Comment by rahlvers** [comment]
Doc generator issue.

**Comment by akf** [comment]
Thanks for all the details! I have a hunch that the parser might be failing to strip whitespace from the path. Please add this to your debug statements and let me know whether abs_local_path has any extraneous characters:  `print(repr(abs_local_path))`

If nothing jumps out at you, it may also be helpful if you could attach a copy of your supplemental markdown document, or at least the Schema_URI_Mapping section. 

I've been developing on MacOS X so I wouldn't be surprised if something non-portable slipped through, although everything in that chunk of code is supposed to be cross-platform.

**Comment by sbs-jms** [comment]
Here's what the path component parse to:
uri: http://redfish.dmtf.org/schemas/swordfish/v1
local: ../../SSM/json_schema/
abs: /cygdrive/c/users/jms/Documents/Clients/SNIA/SSM/json_schema

They look reasonable to me. The Schema_URI_Mapping section is pretty simple (with some of the surrounding content):
\# Excluded Schemas

\# Schema URI Mapping

\#\# Local-repo: http://redfish.dmtf.org/schemas/swordfish/v1 ../../SSM/json_schema/

\# Schema Supplement

**Comment by akf** [comment]
I still haven't set up a test system to try to reproduce this, but in our last round of updates some issues with paths on Windows (not cygwin) surfaced, and I did a pretty thorough review and cleanup of path handling in the doc generator. 

It's possible this fixed your issue, so if you have a chance to re-run it, please check. The updated code was merged into the master branch today.

**Comment by mraineri** [comment]
7/19: Closing; should be fixed and have not heard back from the submitter.
