### ISSUE TITLE
Doc generator generating output based on namespace rather than entity type name

### ISSUE THREAD

**Issue by rahlvers** [DMTF/Redfish-Tools#88]
This can be seen with the Swordfish Capacity schema.  The Capacity schema contains multiple complex types as well as an entity type definition.  
The doc generator is currently extracting the entity type "CapacitySource" and presenting it as the namespace "Capacity".

In this particular schema, the Capacity structure is a complex type (which is currently ignored by the doc generator, a separate issue to address), so the CapacitySource entity is incorrectly presented as Capacity instead.

(It is unclear how the doc generator behaves if there are multiple entity types defined within the same namespace and/or if the complex type inclusion here is triggering this behavior.  Algorithmically this should be evaluated for correctness, or incorrectness.)

**Comment by akf** [comment]
What I expect the doc generator to do is to find "$ref" at the top level of the schema, and generate output based on that. For example, https://redfish.dmtf.org/schemas/Bios.v1_0_3.json has $ref: "#/definitions/Bios", so documentation is output based on definitions/Bios within that file. 

There isn't an intentional fallback in the case where no $ref is found. I thought the $ref was supposed to be there. This could be a misunderstanding on my part. I'll listen for someone more knowledgeable about the spec to comment.

**Comment by rahlvers** [comment]
The json files actually do have the $ref at the top level of the schema, with the correct $ref for the entity type object.  Here's the line in the unversioned file  "$ref": "#/definitions/CapacitySource". 

I can give you a bundle of the latest capacity_v1.xml and corresponding json files to work from.  It's not released right now, so I can't point you to a public copy.

**Comment by akf** [comment]
That would be helpful. I only use the json files, but if you have the bundle already made up of course I can just ignore the XML. I think you have my email address -- afarrell@secondrise.com

**Comment by jautor** [comment]
I do want to look at these cases a bit more.  In the current released Redfish schema there are only a few instances like this, where an embedded object is referenced in another schema (usually Resource, but IPAddress and Redudancy also occur).  I was handling "Status" as a schema fragment in the introduction/preamble section manually, but I was still debating how to handle "IPv4Address", "IPv6Address" and "Location", among others.

Talking with @rahlvers today it seems like perhaps we should gather up these referenced objects and produce a new section after the Schemas which would contain these.  That would keep them separate so there's no confusion about them not being "resources", but rather "supporting definitions".  The section would also enable us to create additional material to include from the supplemental input file.  We may  also want some option to "inline" the definition within the resource (override the separate definition section).

**Comment by jautor** [comment]
As this is a non-trivial enhancement we'll take this into our next round of scheduled enhancements for the tool.

**Comment by mraineri** [comment]
@rahlvers can you check to see if this has been fixed by changes to the doc generator in the last week?

**Comment by akf** [comment]
Just a quick how-to in case this hasn't already been communicated: put the following in either the Introduction or Postscript section of the supplemental input document to specify where the embedded objects should be output: 

[insert_common_objects]

If this isn't present, the doc generator doesn't output them and essentially falls back on old behavior. I just noticed there isn't any mention of this in the repo.
