### ISSUE TITLE
Arrays of enum strings not rendering properly

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#92]
While rare in the Redfish schema, a simple JSON array of strings which specifies enumerations does not render properly (using the HTML output, at least).  "SupportedEthernetCapabilities" property in the "NetworkPort" schema is an example (and the only one I could find!).  

In the published json-schema, the enum string type is included as a $ref to a type (of the same name).  This produces an entry that shows object braces, and breaks this into multiple lines with the property name repeated (this may be the Type exposed, which in this cases is the same name as the property).

name | type | RW | description 
--- | --- | --- | --- 
SupportedEthernetCapabilities [ { | array | read-only | The set of Ethernet capabilities that this port supports.
SupportedEthernetCapabilities | string(enum) | read-write(null) | See SupportedEthernetCapabilities in Property Details, below, for the possible values of this property.
} ]

Moving the string/enum definition inline with the property shows the entry differently, and also causes the Property Details (enum) section to show an empty ":" value for the property name.

JSON schema:
~~~
   "SupportedEthernetCapabilities": {
      "type": "array",
         "items": {
            "anyOf": [{
               "type": "string",
               "enum": [
                  "WakeOnLAN",
                  "EEE" 
                  ],
               "enumDescriptions": {
                  "WakeOnLAN": "Wake on LAN (WoL) is supported on this port.",
                  "EEE": "IEEE 802.3az Energy Efficient Ethernet (EEE) is supported on this port."
               }
           },
           {
              "type": "null"
            }
           ]
       }
   },
~~~

This produces an output like:

name | type | RW | description 
--- | --- | --- | --- 
SupportedEthernetCapabilities [ { | array | read-only | The set of Ethernet capabilities that this port supports.
 | | string(enum) | read-write | See in Property Details, below, for the possible values of this property.
  |   | read-write(null) |  
} ] |   |  

The output for this property should look like this:

name | type | RW | description 
--- | --- | --- | --- 
SupportedEthernetCapabilities [] | array, string(enum) | read-only | The set of Ethernet capabilities that this port supports.  See SupportedEthernetCapabilties in Property Details, below, for the possible values of this property.

**Comment by akf** [comment]
Definitely a bug. I think the type column should (to be consistent) say "array (string (enum), null)". 

It also seems to me that it would be more consistent to have the additional line for the type -- in other words, I would have proposed that the correct output looked like the current output, but without the object brackets {}. 

So, is the rule here to eliminate the extra line when the referenced type is a simple type? "When the names match" would be an easy rule but doesn't quite seem right.

**Comment by akf** [comment]
HostingRoles in ComputerSystem is a good clarifying example, I think. It seems to me very similar to the SupportedEthernetCapabilities example, except that the the referenced type has a slightly different name ("HostingRole") and that it doesn't include the null option. The HTML output currently looks like this: 

<table>
<tr><td><nobr><b>HostingRoles</b> <i>(v1.2+)</i> [ {</nobr></td><td>array</td><td><nobr>read-only</nobr></td><td>The hosing roles that this computer system supports.</td></tr>
--
  | <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<nobr><b>HostingRole</b></nobr></td><td>string<br>(enum)</td><td><nobr>read-write</nobr></td><td>The enumerations of HostingRoles specify different features that the hosting ComputerSystem supports.<br><i>See <a href="#redfish.dmtf.org/schemas/v1/ComputerSystem.json\|details\|HostingRole">HostingRole</a> in Property Details, below, for the possible values of this property.</i></td></tr>
</table>

I think the curly braces indicating an object are inappropriate here, but I'm unsure whether the separate line for "HostingRole" should be maintained.

**Comment by jautor** [comment]
Oh good, you found another example!

Since the type definition (HostingRole above) is just an internal construct for the schema definition, and doesn't actually show up in the payload, I think it should be removed and the "See Property Details" line should append to the single line for the array property.  Having multiple lines makes it appear as if this was an object.

Any other simple arrays (strings, numbers) show up as a single line, the only difference for the reader here should be the reference to the enum list in the Property Details.

**Comment by akf** [comment]
I have a candidate fix -- see the fix_92 branch or pull request #95. 

The output for the SupportedEthernetCapabilities example comes out like this: 

<table>
<tr><td><nobr><b>SupportedEthernetCapabilities</b> [ ] </nobr></td><td>array (string<br>(enum))</td><td><nobr>r\
ead-only</nobr> (null)</td><td>The set of Ethernet capabilities that this port supports.<br><i>See <a href="#re\
dfish.dmtf.org/schemas/v1/NetworkPort.json|details|SupportedEthernetCapabilities">SupportedEthernetCapabilities\
</a> in Property Details, below, for the possible values of this property.</i></td></tr>
</table>

**Comment by akf** [comment]
(and already I see a space that should be a non-breaking space. other than that, how does it look?)

**Comment by jautor** [comment]
Yes, that looks much better...

**Comment by akf** [comment]
Merged into master.
