### ISSUE TITLE
Request: Enhance doc generator to include a separate section for ComplexTypes

### ISSUE THREAD

**Issue by rahlvers** [DMTF/Redfish-Tools#93]
Per conversation with @jautor and @mraineri , the current design excludes inclusion of  ComplexTypes with the rationale that these are used pervasively through the system and that it would not be ideal to have the type definitions replicated throughout the documentation.  

One option suggested is to manually add the definitions to a common header section to address this.    However, in the Swordfish schema set, we have 8 - 10 complex types that are used throughout the system, and both manually documenting these, as well as ensuring that the documentation for these are kept up-to-date is an onerous prospect.

I'd like to request that the complex type definitions be extracted programmatically , and to address the concerns about replicating them, that a new section be added for "Common Structures" (or pick a name you like better) to host the definitions of the common structures.

**Comment by mraineri** [comment]
Probably the easiest way to key off of this is finding an object definition that has an "anyOf" statement, but the first item in the anyOf is NOT and idRef statement...

**Comment by mraineri** [comment]
Example in Settings.json:

```
        "Settings": {
            "anyOf": [
                {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Settings.v1_0_0.json#/definitions/Settings"
                },
                {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Settings.v1_0_2.json#/definitions/Settings"
                },
                {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Settings.v1_0_3.json#/definitions/Settings"
                },
                {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Settings.v1_0_4.json#/definitions/Settings"
                },
                {
                    "$ref": "http://redfish.dmtf.org/schemas/v1/Settings.v1_1_0.json#/definitions/Settings"
                }
            ]
        }
```

**Comment by jautor** [comment]
Looking at this, the condition for referencing the "common object definitions" is even simpler.  If the $ref item is a JSON type "object", you've found one...  The normal rules for searching anyOf entries will apply, so the doc generator would use the highest-version definition.

@rahlvers I was going to suggest having this section auto-generated following the Schemas section - should we allow an option to place it before/after the main schemas?

**Comment by rahlvers** [comment]
Before or after would be good.   For our doc, it would be better to have in front.

**Comment by mraineri** [comment]
@rahlvers can you check to see if this one is fixed now?

**Comment by mraineri** [comment]
Closing; this should be fixed now. Please re-open if the issue still persists.

**Comment by rahlvers** [comment]
Closing... :)
